languageCode = "en-us"
title = "ehab.it"
baseURL = "https://ehab.it"
theme = "dimension"
publishDir = "docs"

[params]
  title = "ehab.it"
  description = 'freelancing, coding, and deep learning'
  logo = "fa-barcode"
  copyright = "2017 ehab.it"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/glenbbaker"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/iepathos"