languageCode = "en-us"
title = "ehab.it"
baseURL = "https://ehab.it"
theme = "dimension"
publishDir = "docs"
canonifyurls = true

[params]
  title = "Glen Baker"
  description = 'freelance software engineer'
  logo = "fa-linux"
  copyright = "2017 ehab.it"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/glenbbaker"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/iepathos"